swagger: "2.0"
info:
  description: "Endpoint per le operazioni sullo shop"
  version: "1.1.0"
  title: "Shop"
basePath: "/shop"
tags:
- name: "Item e prodotti"

paths:
  /shop/items/:
    post:
      tags:
      - "Item e prodotti"
      summary: "Creazione di un nuovo item nello shop"
      description: |
        Gestisce l'inserimento di un nuovo item e i prodotti inclusi.
        
        Richiede permessi ["operator", "shop_write"]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: body
        in: body
        description: "Dati dell'item"
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            category:
              type: string
            relevance:
              type: number
              default: 0
            products:
              type: array
              items:
                type: object
                properties:
                  barcode: 
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  quantity:
                    type: number
                    default: 0
                  target_species:
                    type: array
                    items:
                      type: string
                  images:
                    type: array
                    items:
                      type: object
                      properties:
                        path:
                          type: string
                        description:
                          type: string
                      required: [ path, description ]
                required: [ barcode, name, price, quantity ]
          required:
            - name
            - category
            - products
      responses:
        201:
          description: "Inserito con successo"
          schema:
              $ref: "#/definitions/Item"
          headers:
            location:
              type : string
              description: "Endpoint da cui è possibile accedere all'item"
        400:
          description: "Parametri malformati"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi insufficienti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        409:
          description: "Il barcode di uno dei prodotti è già esistente"
          schema:
            $ref: "definitions/utils.yml#/definitions/FieldErrorMessage"
        500:
          description: "Errore lato server"

    get:
      tags:
      - "Item e prodotti"
      summary: "Ricerca degli item secondo alcuni criteri"
      description: |
        Ricerca tra gli item quelli che soddisfano i criteri richiesti
      produces:
      - "application/json"
      parameters:
      - name: page_size
        in: query
        description: "Numero di item da restituire"
        required: true
        type: number
        format: int
      - name: page_number
        in: query
        description: "Offset per paginazione"
        required: true
        type: number
        format: int
      - name: category
        in: query
        description: "Categoria dell'item"
        type: string
      - name: name
        in: query
        description: "Stringa che l'item deve contenere nel nome"
        type: string
      - name: price_asc
        in: query
        description: "Ordina per prezzo crescente"
        type: boolean
      - name: price_desc
        in: query
        description: "Ordina per prezzo decrescente"
        type: boolean
      - name: name_asc
        in: query
        description: "Ordina per nome in ordine alfabetico"
        type: boolean
      - name: name_desc
        in: query
        description: "Ordina per nome in ordine alfabetico inverso"
        type: boolean
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Item"
        400:
          description: "Parametri malformati"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        500:
          description: "Errore lato server"

  /shop/items/{item_id}:
    get:
      tags:
      - "Item e prodotti"
      summary: "Ricerca di item"
      description: |
        Ricerca di un item dato il suo id.
      produces:
      - "application/json"
      parameters:
      - name: item_id
        in: path
        description: "Id dell'item"
        required: true
        type: string
        format: ObjectId
      responses:
        200:
          description: "Item ricercato"
          schema:
            type: array
            items:
              $ref: "#/definitions/Item"
        400:
          description: "Parametri malformati"
          schema:
            $ref: "#/definitions/ValidatorErrorMessage"
        404:
          description: "Nessun item trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Errore lato server"
    put:
      tags:
      - "Item e prodotti"
      summary: "Modifica delle generalità di un item"
      description: |
        Gestisce la modifica dei dati generali di un item (non dei singoli prodotti).

        Richiede permessi ["operator", "shop_write"]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: item_id
        in: path
        type: string
        format: ObjectId
        required: true
        description: "Id dell'item da modificare"
      - name: body
        in: body
        description: "Dati dell'item"
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            category:
              type: string
            relevance:
              type: number
              format: int
      responses:
        200:
          description: "Modificato con successo"
          schema:
            $ref: "#/definitions/Item"
        400:
          description: "Parametri malformati"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi insufficienti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Nessun item trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Errore lato server"
     
    delete:
      tags:
      - "Item e prodotti"
      summary: "Cancellazione di un item"
      description: |
        Gestisce la cancellazione di un item e di tutti i suoi prodotti associati.

        Richiede permessi ["operator", "shop_write"]
      parameters:
      - name: item_id
        in: path
        type: string
        format: ObjectId
        required: true
        description: "Id dell'item da cancellare"
      responses:
        204:
          description: "Cancellato con successo"
        400:
          description: "Parametri malformati"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi insufficienti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Nessun item trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Errore lato server"

  /shop/items/barcode/{barcode}:
    get:
      tags:
      - "Item e prodotti"
      summary: "Ricerca di un item per barcode di un prodotto"
      description: |
        Ricerca l'item che contiene un determinato prodotto ricercato per barcode.

        Richiede permessi ["operator", "shop_read"]
      produces:
      - "application/json"
      parameters:
      - name: barcode
        in: path
        description: "Barcode del prodotto"
        required: true
        type: string
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Item"
        400:
          description: "Parametri malformati"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi insufficienti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Nessun item trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Errore lato server"

  /shop/items/{item_id}/products/{product_index}:
    put:
      tags:
      - "Item e prodotti"
      summary: "Modifica i dati di un prodotto"
      description: |
        Gestisce la modifica dei dati di un prodotto ricercato a partire dall'item di appartenenza.

        Richiede permessi ["operator", "shop_write"]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: item_id
        in: path
        type: string
        format: ObjectId
        required: true
      - name: product_index
        in: path
        type: number
        format: int
        required: true
      - name: body
        in: body
        description: "Dati da modificare del prodotto"
        schema:
          type: object
          properties:
            barcode:
              type: string
            name:
              type: string
            description:
              type: string
            target_species:
              type: array
              items:
                type: string
            price:
              type: number
            quantity:
              type: number
            images:
              type: array
              items:
                type: object
                properties:
                  path:
                    type: string
                  description:
                    type: string
                required: [ path, description ]
      responses:
        200:
          description: "Modificato con successo"
          schema:
            $ref: "#/definitions/Product"
        400:
          description: "Parametri malformati"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi insufficienti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Nessun item trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Errore lato server"

    delete:
      tags:
      - "Item e prodotti"
      summary: "Cancellazione di un prodotto"
      description: |
        Gestisce la cancellazione di un prodotto ricercato a partire dall'item di appartenenza.

        Richiede permessi ["operator", "shop_write"]
      produces:
      - "application/json"
      parameters:
      - name: item_id
        in: path
        type: string
        format: ObjectId
        required: true
      - name: product_index
        in: path
        type: number
        required: true
      responses:
        204:
          description: "Cancellato con successo"
        303:
          description: |
            Si sta tentando di cancellare un prodotto da un item che ne contiene uno solo.
            Si suggerisce di cancellare l'intero item.
          headers:
            location:
              type : string
              description: "Endpoint a cui richiedere la cancellazione dell'item"
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
        400:
          description: "Parametri malformati"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi insufficienti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Nessun item trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Errore lato server"


  #
  # Inizio categorie
  #
  /shop/categories/:
    get:
      tags:
      - "Categorie"
      summary: "Lista di tutte le categorie"
      description: |
        Restituisce la lista di tutte le categorie disponibili.
      produces:
      - "application/json"
      responses:
        200:
          description: "Lista di tutte le categorie disponibili"
          schema:
            type: array
            items:
              $ref: "#/definitions/Category"
        500:
          description: "Internal server error"
    post:
      tags:
      - "Categorie"
      summary: "Inserimento di categorie"
      description: |
        Creazione di una nuova categoria.

        Richiede permessi ["operator", "shop_write"]
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - name: body
        in: body
        required: true
        description: "Dati della categoria"
        schema:
          $ref: "#/definitions/Category"
      responses:
        201:
          description: "Creato con successo"
          schema:
            $ref: "#/definitions/Category"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        409:
          description: "Categoria con lo stesso nome già esistente"
          schema:
            $ref: "definitions/utils.yml#/definitions/FieldErrorMessage"
        500:
          description: "Internal server error"
  /shop/categories/{category}:
    put:
      tags:
      - "Categorie"
      summary: "Aggiornamento di categorie"
      description: |
        Aggiornamento di una categoria.

        Richiede permessi ["operator", "shop_write"]
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - name: category
        description: "Categoria da aggiornare"
        in: path
        type: string
        required: true
      - name: body
        in: body
        description: "Dati da aggiornare della categoria"
        schema:
          $ref: "#/definitions/Category"
      responses:
        200:
          description: "Aggiornato con successo"
          schema:
            $ref: "#/definitions/Category"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Categoria non esistente"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"
    delete:
      tags:
      - "Categorie"
      summary: "Cancellazione di categorie"
      description: |
        Cancellazione di una categoria.

        Richiede permessi ["operator", "shop_write"]
      parameters:
      - name: category
        description: "Categoria da cancellare"
        in: path
        type: string
        required: true
      responses:
        204:
          description: "Cancellato con successo"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Categoria non esistente"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"


definitions:

  Category:
    type: object
    properties:
      name:
        type: string
      icon:
        type: string
        format: byte
    required:
      - name
      - icon

  Item:
    type: object
    properties:
      id:
        $ref: "definitions/utils.yml#/definitions/ObjectId"
      name:
        type: string
      description:
        type: string
      category:
        type: string
      relevance:
        type: number
      products:
        type: array
        items:
            $ref: "#/definitions/Product"
    required:
      - id
      - name
      - description
      - category
      - relevance
      - products

  Product:
    type: object
    properties:
      barcode: 
        type: string
      name:
        type: string
      description:
        type: string
      images:
        type: array
        items:
          type: object
          properties:
            path:
              type: string
            description:
              type: string
          required: [ path, description ]
      target_species:
        type: array
        items:
          type: string
      price:
        type: number
      quantity:
        type: number
    required: [ barcode, name, description, images, target_species, price, quantity ]