swagger: "2.0"
info:
  description: "Endpoint per le operazioni sulle specie"
  version: "1.0.0"
  title: "Species"

paths:
  /species/:
    post:
      tags:
        - "Species"
      summary: "Creazione di una nuova specie"
      description: | 
        Gestisce l'inserimento di una specie

        Richiede permesso [ ["admin"] ]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: body
        in: body
        description: "Dati della specie"
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
          required: [ name ]
      responses:
        201:
          description: "Creato con successo"
          schema:
            $ref: "#/definitions/SpeciesData"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        409:
          description: "Specie con lo stesso nome esistente"
          schema:
            $ref: "definitions/utils.yml#/definitions/FieldErrorMessage"
        500:
          description: "Internal server error"
    get:
      tags:
      - "Species"
      summary: "Ricerca delle specie"
      description: "Gestisce la ricerca delle specie con la possibilità di cercare per nome"
      produces:
      - "application/json"
      parameters:
      - name: name
        in: query
        description: "Nome della specie"
        required: false
        type: string
      responses:
        200:
          description: "Trovato con successo"
          schema:
            $ref: "#/definitions/SpeciesData"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"
  /species/{name}/:
    put:
      tags:
        - "Species"
      summary: "Modifica di una specie"
      description: |
        Gestisce la modifica di una specie tramite nome

        Richiede permesso [ ["admin"] ]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: name
        in: path
        description: "Nome della specie"
        required: true
        type: string
      - name: body
        in: body
        description: "Dati della specie"
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
      responses:
        200:
          description: "Modificato con successo"
          schema:
            $ref: "#/definitions/SpeciesData"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"
    delete:
      tags:
        - "Species"
      summary: "Cancellazione di una specie"
      description:  |
        Gestisce la cancellazione di una specie tramite nome

        Richiede permesso [ ["admin"] ]
      produces:
      - "application/json"
      parameters:
      - name: name
        in: path
        description: "Nome della specie"
        required: true
        type: string
      responses:
        204:
          description: "Cancellato con successo"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"

definitions:
  SpeciesData:
    type: object
    properties:
      name:
        type: string
    required: [ name ]