swagger: "2.0"
info:
  description: "Endpoint per le operazioni sugli user"
  version: "1.0.0"
  title: "User"

paths:
  /users/customers/:
    post:
      tags:
      - "Clienti"
      summary: "Creazione di un nuovo cliente"
      description: "Gestisce l'inserimento di un cliente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: body
        in: body
        description: "Dati del cliente"
        required: true
        schema:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
            email:
              type: string
              format: email
            name:
              type: string
            surname:
              type: string
            gender:
              type: string
              enum: ["m", "f", "altro"]
            phone:
              type: string
            address:
              $ref: "#definitions/Address"
          required: [ username, password, email, name, surname ]
      responses:
        201:
          description: "Creato con successo"
          schema:
            $ref: "#/definitions/CustomerUserAll"
          headers:
            location:
              type : string
              description: "Endpoint da cui è possibile accedere ai dati dell'utente"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        409:
          description: "Cliente con stesso username/email esistente"
          schema:
            $ref: "definitions/utils.yml#/definitions/FieldErrorMessage"
        500:
          description: "Internal server error"
          
  /users/customers/{username}:
    get:
      tags:
      - "Clienti"
      summary: "Ricerca di un cliente"
      description: |
        Gestisce la ricerca di tutti i dati di un cliente tramite username

        Richiede permessi [ ["user"], ["admin"] ]
      produces:
      - "application/json"
      parameters:
      - name: username
        in: query
        description: "Username del cliente"
        required: true
        type: string
      responses:
        200:
          description: "Trovato con successo"
          schema:
              $ref: "#/definitions/CustomerUserAll"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"
      
    put:
      tags:
      - "Clienti"
      summary: "Modifica di un cliente"
      description: |
        Gestisce la modifica di un cliente tramite criterio di ricerca con username
        
        Richiede permessi [ ["user"], ["admin"] ]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: username
        in: query
        description: "Username del cliente"
        required: true
        type: string
      - name: body
        in: body
        description: "Dati del cliente"
        required: true
        schema:
          type: object
          properties:
            password:
              type: string
            email:
              type: string
            name:
              type: string
            surname:
              type: string
            gender:
              type: string
            phone:
              type: string
            address:
              $ref: "#/definitions/Address"
            enabled:
              type: boolean
              description: Account abilitato (modificabile solo dagli amministratori)
            permissions:
              description: Permessi dell'utente (modificabile solo dagli amministratori)
              type: array
              items:
                type: string
      responses:
        200:
          description: "Modificato con successo"
          schema:
            $ref: "#/definitions/CustomerUserAll"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"

    delete:
      tags:
      - "Clienti"
      summary: "Cancellazione di un cliente"
      description: |
        Gestisce la cancellazione di un cliente tramite criterio di ricerca con username
        
        Richiede permessi [ ["user"], ["admin"] ]
      produces:
      - "application/json"
      parameters:
      - name: username
        in: query
        description: "Username del cliente"
        required: true
        type: string
      responses:
        204:
          description: "Cancellato con successo"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"          
        500:
          description: "Internal server error"


########################
### INIZIO OPERATORI ###
########################

  /users/operators/:
    post:
      tags:
      - "Operatori"
      summary: "Creazione di un nuovo operatore"
      description: |
        Gestisce l'inserimento di un operatore

        Richiede permesso [ ["admin"] ]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: body
        in: body
        description: "Dati dell'operatore"
        required: true
        schema:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
            email:
              type: string
              format: email
            name:
              type: string
            surname:
              type: string
            gender:
              type: string
              enum: ["m", "f", "altro"]
            phone:
              type: string
            permissions:
              type: array
              items:
                type: string
            role:
              type: string
            services_id:
              type: array
              items:
                $ref: "definitions/utils.yml#/definitions/ObjectId"
          required: [ username, password, email, name, surname ]
      responses:
        201:
          description: "Creato con successo"
          schema:
            $ref: "#/definitions/OperatorUserAll"
          headers:
            location:
              type : string
              description: "Endpoint da cui è possibile accedere ai dati dell'utente"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:          
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:          
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        409:
          description: "Operatore esistente"
          schema:
            $ref: "definitions/utils.yml#/definitions/FieldErrorMessage"
        500:
          description: "Internal server error"
          
  /users/operators/{username}:
    get:
      tags:
      - "Operatori"
      summary: "Ricerca di un operatore"
      description: |
        Gestisce la ricerca di un operatore tramite username

        Richiede permessi [ ["operator"], ["admin"] ]
      produces:
      - "application/json"
      parameters:
      - name: username
        in: query
        description: "Username dell'operatore"
        required: true
        type: string
      responses:
        200:
          description: "Trovato con successo"
          schema:
              $ref: "#/definitions/OperatorUserAll"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"
      
    put:
      tags:
      - "Operatori"
      summary: "Modifica di un operatore"
      description: |
        Gestisce la modifica di un operatore tramite criterio di ricerca con username
        
        Richiede permesso [ ["operator"], ["admin"] ]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: username
        in: query
        description: "Username dell'operatore"
        required: true
        type: string
      - name: body
        in: body
        description: "Dati dell'operatore"
        required: true
        schema:
          type: object
          properties:
            password:
              type: string
            email:
              type: string
            name:
              type: string
            surname:
              type: string
            gender:
              type: string
            phone:
              type: string
            role:
              type: string
            services_id:
              type: array
              items:
                $ref: "definitions/utils.yml#/definitions/ObjectId"
            enabled:
              type: boolean
            permissions:
              description: Permessi dell'utente (modificabile solo dagli amministratori)
              type: array
              items:
                type: string
      responses:
        200:
          description: "Modificato con successo"
          schema:
            $ref: "#/definitions/OperatorUserAll"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"
    
    delete:
      tags:
      - "Operatori"
      summary: "Cancellazione di un operatore"
      description: |
        Gestisce la cancellazione di un operatore tramite criterio di ricerca con username
        
        Richiede permessi [ ["admin"] ]
      produces:
      - "application/json"
      parameters:
      - name: username
        in: query
        description: "Username dell'operatore"
        required: true
        type: string
      responses:
        204:
          description: "Cancellato con successo"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"

  /users/profiles/{username}:
    get:
      tags:
      - "Profilo pubblico"
      summary: "Ricerca del profilo pubblico di un utente"
      description: |
        Gestisce la ricerca dei dati pubblici di un utente
      produces:
      - "application/json"
      parameters:
      - name: username
        in: query
        description: "Username dell'utente"
        required: true
        type: string
      responses:
        200:
          description: "Trovato con successo"
          schema:
            type: object
            properties:
              ifCustomer:
                $ref: "#/definitions/CustomerUserProfile"
              ifOperator:
                $ref: "#/definitions/OperatorUserProfile"
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"

  /users/permissions/:
    get:
      tags:
      - "Permessi"
      summary: "Ricerca dei dati di tutti i permessi"
      description: |
        Restituisce i dati associati a tutti i permessi.

        Richiede autenticazione
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: "Trovato con successo"
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
              required: [ name ]
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"

  /users/permissions/{permission_name}:
    get:
      tags:
      - "Permessi"
      summary: "Ricerca dei dati di un permesso"
      description: |
        Restituisce i dati associati ad un permesso.

        Richiede permessi [ ["operator"] ], [ ["admin"] ]
      produces:
      - "application/json"
      parameters:
      - name: permission_name
        in: path
        required: true
        type: string
      responses:
        200:
          description: "Trovato con successo"
          schema:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
            required: [ name ]
        400:
          description: "Input malformato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ValidationErrorMessage"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Permessi mancanti"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        404:
          description: "Non trovato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"

  /users/customers/enable-me:
    get:
      tags:
      - "Operatori"
      summary: "Ricerca di un operatore"
      description: |
        Gestisce l'attivazione dell'utenza di un cliente.

        Richiede permessi [ ["to_activate_user"] ], []
      produces:
      - "application/json"
      responses:
        200:
          description: "Attivato con successo"
          schema:
              $ref: "#/definitions/CustomerUserAll"
        401:
          description: "Non autenticato"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        403:
          description: "Utenza già attiva"
          schema:
            $ref: "definitions/utils.yml#/definitions/ErrorMessage"
        500:
          description: "Internal server error"


definitions:

  CustomerUserAll:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      name:
        type: string
      surname:
        type: string
      gender:
        type: string
      phone:
        type: string
      permissions:
        type: array
        items:
          type: string
      enabled:
        type: boolean
      address:
        $ref: "#/definitions/Address"
    required: [ username, email, name, surname, permissions, enabled ]

  CustomerUserProfile:
    type: object
    properties:
      username:
        type: string
      name:
        type: string
      surname:
        type: string
    required: [ username, name, surname ]

  OperatorUserAll:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      name:
        type: string
      surname:
        type: string
      gender:
        type: string
      phone:
        type: string
      permissions:
        type: array
        items:
          type: string
      enabled:
        type: boolean
      role:
        type: string
      services_id:
        type: array
        items:
          $ref: "definitions/utils.yml#/definitions/ObjectId"
    required: [ username, email, phone, name, surname, permissions, enabled, role, services_id ]

  OperatorUserProfile:
    type: object
    properties:
      username:
        type: string
      name:
        type: string
      surname:
        type: string
      email:
        type: string
      phone:
        type: string
      role:
        type: string
      services_id:
        type: array
        items:
          $ref: "definitions/utils.yml#/definitions/ObjectId"
    required: [ username, name, surname, role, services_id, email, phone, address ]
  
  Address:
    type: object
    properties:
      city:
        type: string
      street:
        type: string
      number:
        type: string
      postal_code:
        type: string
