name: Test vari ed eventuali

on: [push]

env:
  MONGODB_URL: mongodb://localhost:27017/
  MONGODB_DATABASE_NAME: AnimalHouse
  JWT_ALGORITHM: HS256
  ACCESS_TOKEN_KEY: ${{secrets.ACCESS_TOKEN_KEY}}
  REFRESH_TOKEN_KEY: ${{secrets.REFRESH_TOKEN_KEY}}
  ACCESS_TOKEN_EXP: 10m
  REFRESH_TOKEN_EXP: 14d

jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: 4.4
        mongodb-db: AnimalHouse

    - run: npm ci
    - run: npm run initdb
    - run: npm test